import { Inter, Source_Code_Pro} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header"
import Hero from "@/components/Hero"
import ButtonGradient from "../assets/svg/ButtonGradient"
const inter = Inter({ subsets: ["latin"] });
const sc = Source_Code_Pro({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${sc.className} ${inter.className}`}>
        <div className="fixed w-full">
          <Header/>
        </div>
        {children}
      </body>
    </html>
  );
}
